name: update-and-push
description: >-
  This action supports update of target repository with files in source repository.
inputs:
  transfer_map:
    description: >-
      [Optional] Path to configuration file describing transformation
      of directory structure from source to destionation repository.
      If present, overrides 'source_directory' and 'target_directory'
    required: false
    default: ''
  source_directory:
    description: >-
      [Optional] Directory to use as base for update
    required: false
    default: '.'
  target_user:
    description: >-
      [Optional] Name of the user/organization owning the target repository.
      (Default: same as the owner of the source repository)
    required: false
    default: ''
  target_repository:
    description: Name of the target repository
    required: true
  commit_email:
    description: E-mail used in git commit
    required: true
  target_server:
    description: 'Target git server'
    required: false
    default: ''
  target_branch:
    description: >-
      [Optional] Target branch name (default: "main")
    required: false
    default: main
  commit_message:
    description: >-
      [Optional] Commit message. ${ORIGIN_COMMIT} is replaced by the URL@commit in the origin repo triggering the action
    required: false
    default: 'Update from ${ORIGIN_COMMIT}'
  target_directory:
    description: '[Optional] Directory in the target repository to update'
    required: false
    default: ''
  create_target_branch:
    description: '[Optional] Boolean indicating whether to create the target branch if it does not exist'
    required: false
    default: 'false'
  exclude_filter:
    description: '[Optional] Name of file containing rsync-style exclude list'
    required: false
    default: ''
        
runs:
  using: docker
  image: Dockerfile

branding:
  icon: git-commit
  color: green
